server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_flashsale
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true