server:
  port: 8084
spring:
  datasource:
    payment:
      jdbc-url: jdbc:postgresql://localhost:5432/db_trx_payment
      username: postgres
      password: admin
    cart:
      jdbc-url: jdbc:postgresql://localhost:5432/db_cart
      username: postgres
      password: admin
    product:
      jdbc-url: jdbc:postgresql://localhost:5432/db_mst_product
      username: postgres
      password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
midtrans:
  server-key: SB-Mid-server-oQ9buJM9VzkIKUJxEv7_7wmJ
  charge:
    api-url: https://api.sandbox.midtrans.com/v2/charge
  status:
    api-url: https://api.sandbox.midtrans.com/v2/%s/status