spring:
  datasource:
    cart:
      jdbc-url: jdbc:postgresql://localhost:5432/db_cart
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver
    product:
      jdbc-url: jdbc:postgresql://localhost:5432/db_mst_product
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver
    user:
      jdbc-url: jdbc:postgresql://localhost:5432/db_mst_user
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
